apiVersion: v1
kind: Namespace
metadata:
  name: eshopondapr
  labels:
    istio.io/rev: asm-1-22
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key": "reservedFor", "operator": "Equal", "effect": "NoSchedule", "value": "apps"}]'
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: eshopondapr
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://bjdcsa.azurecr.io/helm
  passCredentials: true
  secretRef:
    name: https-credentials
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name:  eshopondapr
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: eshopondapr
  chart:
    spec:
      chart: eShopOnDapr
      version: '>=2.0.0'
      sourceRef:
        kind: HelmRepository
        name:  eshopondapr
        namespace: flux-system
      interval: 1m
  values:
    hostname: shop.bjdazure.tech
    istioGateway: aks-istio-ingress/default-bjdazure-tech-gw